/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewSwing;

import controllers.LocadoraController;
import models.entities.ClienteEntity;
import models.entities.LocadoraEntity;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Mamonha
 */
public class LocadoraFrame extends javax.swing.JFrame {

    /**
     * Creates new form LocadoraFrame
     */
    public LocadoraFrame() {
        initComponents();
    }
    private LocadoraController locadoraController = new LocadoraController();
    private LocadoraEntity locadora = new LocadoraEntity();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        VisualizarLocadoraBtn = new javax.swing.JButton();
        CadastrarLocadoraBtn = new javax.swing.JButton();
        GerenciarLocadoraBtn = new javax.swing.JButton();
        VoltarLocadora = new javax.swing.JButton();
        CardPanel = new javax.swing.JPanel();
        CadLocadora = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NomeLocadora = new javax.swing.JTextField();
        EmailLocadora = new javax.swing.JTextField();
        CnpjLocadora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VoltarRegistrarLocadora = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        TelefoneLocadora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        VisualizaLocadora = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListarLocadoras = new javax.swing.JTable();
        GerenciarLocadoras = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaGerenciarLocadoras = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        EditarLocadoraBtn = new javax.swing.JButton();
        RemoverLocadoraBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(48, 191, 88));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image 1.png"))); // NOI18N

        VisualizarLocadoraBtn.setBackground(new java.awt.Color(125, 223, 32));
        VisualizarLocadoraBtn.setText("Visualizar Locadoras");
        VisualizarLocadoraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarLocadoraBtnActionPerformed(evt);
            }
        });

        CadastrarLocadoraBtn.setBackground(new java.awt.Color(125, 223, 32));
        CadastrarLocadoraBtn.setText("Cadastrar Locadora");
        CadastrarLocadoraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarLocadoraBtnActionPerformed(evt);
            }
        });

        GerenciarLocadoraBtn.setBackground(new java.awt.Color(125, 223, 32));
        GerenciarLocadoraBtn.setText("Gerenciar Locadoras");
        GerenciarLocadoraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarLocadoraBtnActionPerformed(evt);
            }
        });

        VoltarLocadora.setBackground(new java.awt.Color(125, 223, 32));
        VoltarLocadora.setText("Voltar");
        VoltarLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarLocadoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VoltarLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarLocadoraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GerenciarLocadoraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisualizarLocadoraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(CadastrarLocadoraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(VisualizarLocadoraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(GerenciarLocadoraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(VoltarLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        CardPanel.setLayout(new java.awt.CardLayout());

        CadLocadora.setBackground(new java.awt.Color(5, 102, 44));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Registrar Locadora");

        jLabel3.setText("Nome");

        NomeLocadora.setBackground(new java.awt.Color(204, 204, 204));
        NomeLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeLocadoraActionPerformed(evt);
            }
        });

        EmailLocadora.setBackground(new java.awt.Color(204, 204, 204));
        EmailLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailLocadoraActionPerformed(evt);
            }
        });

        CnpjLocadora.setBackground(new java.awt.Color(204, 204, 204));
        CnpjLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnpjLocadoraActionPerformed(evt);
            }
        });

        jLabel4.setText("Email");

        jLabel5.setText("CNPJ");

        VoltarRegistrarLocadora.setText("Voltar");
        VoltarRegistrarLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarRegistrarLocadoraActionPerformed(evt);
            }
        });

        jButton7.setText("Cadastrar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        TelefoneLocadora.setBackground(new java.awt.Color(204, 204, 204));
        TelefoneLocadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneLocadoraActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(VoltarRegistrarLocadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(EmailLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4))
                            .addComponent(CnpjLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelefoneLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel7)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NomeLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CnpjLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelefoneLocadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VoltarRegistrarLocadora)
                    .addComponent(jButton7))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout CadLocadoraLayout = new javax.swing.GroupLayout(CadLocadora);
        CadLocadora.setLayout(CadLocadoraLayout);
        CadLocadoraLayout.setHorizontalGroup(
            CadLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadLocadoraLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        CadLocadoraLayout.setVerticalGroup(
            CadLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadLocadoraLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        CardPanel.add(CadLocadora, "card2");

        VisualizaLocadora.setBackground(new java.awt.Color(5, 102, 44));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Lista de Locadoras");

        ListarLocadoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(ListarLocadoras);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(341, 341, 341))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VisualizaLocadoraLayout = new javax.swing.GroupLayout(VisualizaLocadora);
        VisualizaLocadora.setLayout(VisualizaLocadoraLayout);
        VisualizaLocadoraLayout.setHorizontalGroup(
            VisualizaLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizaLocadoraLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        VisualizaLocadoraLayout.setVerticalGroup(
            VisualizaLocadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisualizaLocadoraLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        CardPanel.add(VisualizaLocadora, "card3");

        GerenciarLocadoras.setBackground(new java.awt.Color(5, 102, 44));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        TabelaGerenciarLocadoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TabelaGerenciarLocadoras);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Gerenciar Locadoras");

        EditarLocadoraBtn.setBackground(new java.awt.Color(125, 223, 32));
        EditarLocadoraBtn.setText("Editar");
        EditarLocadoraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarLocadoraBtnActionPerformed(evt);
            }
        });

        RemoverLocadoraBtn.setBackground(new java.awt.Color(125, 223, 32));
        RemoverLocadoraBtn.setText("Remover");
        RemoverLocadoraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverLocadoraBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditarLocadoraBtn)
                    .addComponent(RemoverLocadoraBtn))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(341, 341, 341))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(EditarLocadoraBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoverLocadoraBtn))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout GerenciarLocadorasLayout = new javax.swing.GroupLayout(GerenciarLocadoras);
        GerenciarLocadoras.setLayout(GerenciarLocadorasLayout);
        GerenciarLocadorasLayout.setHorizontalGroup(
            GerenciarLocadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerenciarLocadorasLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        GerenciarLocadorasLayout.setVerticalGroup(
            GerenciarLocadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerenciarLocadorasLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        CardPanel.add(GerenciarLocadoras, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1662, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(CardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizarLocadoraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarLocadoraBtnActionPerformed
        CardPanel.removeAll();
        CardPanel.add(VisualizaLocadora);
        CardPanel.repaint();
        CardPanel.revalidate();

        List<LocadoraEntity> locadoras = locadoraController.index();

        // Define o modelo de tabela com as colunas
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nome");
        model.addColumn("CNPJ");
        model.addColumn("Telefone");
        model.addColumn("Email");

        for (LocadoraEntity locadora : locadoras) {
            model.addRow(new Object[]{locadora.getId(), locadora.getNome(), locadora.getCnpj(), locadora.getTelefone(), locadora.getEmail()});
        }
        System.out.println(model);
        ListarLocadoras.setModel(model);
    }//GEN-LAST:event_VisualizarLocadoraBtnActionPerformed

    private void CadastrarLocadoraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarLocadoraBtnActionPerformed
        CardPanel.removeAll();
        CardPanel.add(CadLocadora);
        CardPanel.repaint();
        CardPanel.validate();
    }//GEN-LAST:event_CadastrarLocadoraBtnActionPerformed

    private void GerenciarLocadoraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarLocadoraBtnActionPerformed
        CardPanel.removeAll();
        CardPanel.add(GerenciarLocadoras);
        CardPanel.repaint();
        CardPanel.validate();

        updateLocadoraCliente();
    }//GEN-LAST:event_GerenciarLocadoraBtnActionPerformed

    private void VoltarLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarLocadoraActionPerformed
        MainFrame frame = new MainFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarLocadoraActionPerformed

    private void NomeLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeLocadoraActionPerformed

    }//GEN-LAST:event_NomeLocadoraActionPerformed

    private void EmailLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailLocadoraActionPerformed

    }//GEN-LAST:event_EmailLocadoraActionPerformed
    public void updateLocadoraCliente() {
        List<LocadoraEntity> locadoras = locadoraController.index();

        // Define o modelo de tabela com as colunas
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nome");
        model.addColumn("CNPJ");
        model.addColumn("Email");
        model.addColumn("Telefone");

        for (LocadoraEntity locadora : locadoras) {
            model.addRow(new Object[]{locadora.getId(), locadora.getNome(), locadora.getCnpj(), locadora.getEmail(), locadora.getTelefone()});
        }

        TabelaGerenciarLocadoras.setModel(model);
    }
    private void CnpjLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnpjLocadoraActionPerformed

    }//GEN-LAST:event_CnpjLocadoraActionPerformed

    private void VoltarRegistrarLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarRegistrarLocadoraActionPerformed
        MainFrame frame = new MainFrame();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarRegistrarLocadoraActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        locadora.setNome(NomeLocadora.getText());
        locadora.setEmail(EmailLocadora.getText());
        locadora.setTelefone(TelefoneLocadora.getText());
        locadora.setCnpj(CnpjLocadora.getText());
        locadoraController.create(locadora);
        JOptionPane.showMessageDialog(this, "Locadora criada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void EditarLocadoraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarLocadoraBtnActionPerformed
        int colunaSelected = TabelaGerenciarLocadoras.getSelectedRow();

        Object valorColuna = TabelaGerenciarLocadoras.getValueAt(colunaSelected,1);
        Long idLocadora = (long)TabelaGerenciarLocadoras.getValueAt(colunaSelected,0);
        System.out.println(valorColuna);
        if(valorColuna != null){
            ModalEditarLocadora modal = new ModalEditarLocadora(this, idLocadora);
            modal.setVisible(true);
        }
    }//GEN-LAST:event_EditarLocadoraBtnActionPerformed

    private void RemoverLocadoraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverLocadoraBtnActionPerformed
        int colunaSelected = TabelaGerenciarLocadoras.getSelectedRow();

        Object valorColuna = TabelaGerenciarLocadoras.getValueAt(colunaSelected,1);
        Long idLocadora = (long)TabelaGerenciarLocadoras.getValueAt(colunaSelected,0);

        if(valorColuna != null){
            ModalRemoverCliente modalRemover = new ModalRemoverCliente(this);
            modalRemover.setVisible(true);
            if(modalRemover.isConfirmado()){
                locadoraController.delete(locadoraController.findById(idLocadora));
                JOptionPane.showMessageDialog(this, "Locadora deletada com sucesso!");
                modalRemover.setVisible(false);
                repaint();
            }else{
                modalRemover.setVisible(false);
            }

        }
    }//GEN-LAST:event_RemoverLocadoraBtnActionPerformed

    private void TelefoneLocadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneLocadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneLocadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocadoraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadLocadora;
    private javax.swing.JButton CadastrarLocadoraBtn;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JTextField CnpjLocadora;
    private javax.swing.JButton EditarLocadoraBtn;
    private javax.swing.JTextField EmailLocadora;
    private javax.swing.JButton GerenciarLocadoraBtn;
    private javax.swing.JPanel GerenciarLocadoras;
    private javax.swing.JTable ListarLocadoras;
    private javax.swing.JTextField NomeLocadora;
    private javax.swing.JButton RemoverLocadoraBtn;
    private javax.swing.JTable TabelaGerenciarLocadoras;
    private javax.swing.JTextField TelefoneLocadora;
    private javax.swing.JPanel VisualizaLocadora;
    private javax.swing.JButton VisualizarLocadoraBtn;
    private javax.swing.JButton VoltarLocadora;
    private javax.swing.JButton VoltarRegistrarLocadora;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
